import { User } from '@/services/authService';
import { PlanoAula } from '@/services/planoService';

// Usuários mockados

export interface Disciplina {
  id: string;
  nome: string;
  codigo?: string;
  cor?: string;
  serie: string;
  cargaHoraria: number;
  status: 'ativa' | 'inativa';
}


// Planos mockados
export const MOCK_PLANOS: PlanoAula[] = [
  {
    _id: 'p1',
    professorId: '1',
    professorNome: 'Maria Silva',
    disciplina: 'Matemática',
    turma: '1ª Série',
    mesAno: '2026-03',
    objetivos: 'Desenvolver o raciocínio lógico-matemático através de operações básicas e resolução de problemas contextualizados.',
    conteudo: 'Números naturais, adição e subtração, problemas do cotidiano.',
    avaliacao: 'Avaliação contínua através de exercícios em sala e participação.',
    semanas: [
      { numero: 1, metodologia: 'Aula expositiva com material concreto (blocos lógicos). Atividade em duplas para contagem.', recursos: 'Blocos lógicos, quadro branco, fichas numeradas.' },
      { numero: 2, metodologia: 'Jogos matemáticos em grupo. Resolução de problemas no caderno.', recursos: 'Jogos de tabuleiro, caderno, lápis coloridos.' },
      { numero: 3, metodologia: 'Atividade prática: mercadinho simulado para trabalhar adição e subtração.', recursos: 'Cédulas e moedas de brinquedo, etiquetas de preço.' },
      { numero: 4, metodologia: 'Revisão com quiz interativo e avaliação individual escrita.', recursos: 'Projetor, folhas de avaliação impressas.' },
    ],
    status: 'finalizado',
    criadoEm: '2026-02-28T10:00:00Z',
    atualizadoEm: '2026-03-05T14:30:00Z',
  },
  {
    _id: 'p2',
    professorId: '1',
    professorNome: 'Maria Silva',
    disciplina: 'Português',
    turma: '2ª Série',
    mesAno: '2026-03',
    objetivos: 'Aprimorar a leitura e interpretação de textos curtos, ampliando o vocabulário.',
    conteudo: 'Leitura de contos e fábulas, interpretação textual, ortografia.',
    avaliacao: 'Produção textual e leitura em voz alta.',
    semanas: [
      { numero: 1, metodologia: 'Roda de leitura com conto "A Cigarra e a Formiga". Discussão oral.', recursos: 'Livro de fábulas, almofadas para roda de leitura.' },
      { numero: 2, metodologia: 'Atividade de reescrita do conto com desenho. Trabalho individual.', recursos: 'Folhas pautadas, lápis de cor, borracha.' },
      { numero: 3, metodologia: 'Ditado de palavras do conto. Atividade em duplas de ortografia.', recursos: 'Caderno, dicionário ilustrado.' },
    ],
    status: 'rascunho',
    criadoEm: '2026-03-01T08:00:00Z',
    atualizadoEm: '2026-03-01T08:00:00Z',
  },
  {
    _id: 'p3',
    professorId: '2',
    professorNome: 'Carlos Oliveira',
    disciplina: 'Ciências',
    turma: '3ª Série',
    mesAno: '2026-03',
    objetivos: 'Compreender o ciclo da água e sua importância para o meio ambiente.',
    conteudo: 'Ciclo da água, estados físicos, preservação ambiental.',
    avaliacao: 'Maquete do ciclo da água e apresentação oral.',
    semanas: [
      { numero: 1, metodologia: 'Vídeo sobre ciclo da água seguido de debate em sala.', recursos: 'Projetor, vídeo educativo, caderno.' },
      { numero: 2, metodologia: 'Experimento: evaporação e condensação com materiais simples.', recursos: 'Copos, água, plástico filme, gelo.' },
      { numero: 3, metodologia: 'Construção de maquete do ciclo da água em grupos.', recursos: 'Isopor, tinta guache, algodão, cola.' },
      { numero: 4, metodologia: 'Apresentação das maquetes e avaliação oral.', recursos: 'Maquetes prontas, rubrica de avaliação.' },
    ],
    status: 'finalizado',
    criadoEm: '2026-02-25T09:00:00Z',
    atualizadoEm: '2026-03-04T11:00:00Z',
  },
  {
    _id: 'p4',
    professorId: '1',
    professorNome: 'Maria Silva',
    disciplina: 'História',
    turma: '1ª Série',
    mesAno: '2026-02',
    objetivos: 'Reconhecer a importância da família e da comunidade na formação da identidade.',
    conteudo: 'Família, comunidade, identidade cultural.',
    avaliacao: 'Desenho da árvore genealógica e relato oral.',
    semanas: [
      { numero: 1, metodologia: 'Conversa sobre família. Cada aluno apresenta foto da família.', recursos: 'Fotos trazidas de casa, mural da sala.' },
      { numero: 2, metodologia: 'Construção da árvore genealógica com recortes e colagem.', recursos: 'Cartolina, cola, tesoura, revistas.' },
    ],
    status: 'finalizado',
    criadoEm: '2026-01-28T10:00:00Z',
    atualizadoEm: '2026-02-10T16:00:00Z',
  },
];
export const MOCK_USERS: (User & { senha?: string })[] = [
  {
    id: 'p_100',
    nome: 'AMANDA DE SENA GUSMAO',
    email: 'amanda@sage.com',
    cpf: '100.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_1', 'd_2', 'd_3', 'd_4'],
    senha: 'sage',
  },
  {
    id: 'p_101',
    nome: 'ANA CRISTINA DE SOUZA LIMA',
    email: 'ana@sage.com',
    cpf: '101.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_5', 'd_6', 'd_7', 'd_8'],
    senha: 'sage',
  },
  {
    id: 'p_102',
    nome: 'ANDREIA FELIZARDO LIMA',
    email: 'andreia@sage.com',
    cpf: '102.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_9', 'd_10', 'd_11'],
    senha: 'sage',
  },
  {
    id: 'p_103',
    nome: 'BRENDA SILVA MARQUES VIEIRA',
    email: 'brenda@sage.com',
    cpf: '103.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_9', 'd_12', 'd_13', 'd_14', 'd_15'],
    senha: 'sage',
  },
  {
    id: 'p_104',
    nome: 'DIEGO CAVALCANTE DE OLIVEIRA',
    email: 'diego@sage.com',
    cpf: '104.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_16', 'd_17'],
    senha: 'sage',
  },
  {
    id: 'p_105',
    nome: 'EMANOEL MIRANDA DE OLIVEIRA',
    email: 'emanoel@sage.com',
    cpf: '105.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_18', 'd_19'],
    senha: 'sage',
  },
  {
    id: 'p_106',
    nome: 'ERIK WILLER ALVES RODRIGUES',
    email: 'erik@sage.com',
    cpf: '106.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_20', 'd_21', 'd_22', 'd_23', 'd_7'],
    senha: 'sage',
  },
  {
    id: 'p_107',
    nome: 'FRANCISCA TEIXEIRA RODRIGUES',
    email: 'francisca@sage.com',
    cpf: '107.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_24', 'd_25', 'd_26', 'd_27', 'd_28'],
    senha: 'sage',
  },
  {
    id: 'p_108',
    nome: 'FRANCISCO ALFREDO NICOLAU FILHO',
    email: 'francisco@sage.com',
    cpf: '108.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_29', 'd_30', 'd_31', 'd_32', 'd_33'],
    senha: 'sage',
  },
  {
    id: 'p_109',
    nome: 'HELIO GOMES E SILVA',
    email: 'helio@sage.com',
    cpf: '109.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_34', 'd_25', 'd_35', 'd_36', 'd_37', 'd_38', 'd_39'],
    senha: 'sage',
  },
  {
    id: 'p_110',
    nome: 'IASMIN CARMO RODRIGUES',
    email: 'iasmin@sage.com',
    cpf: '110.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_40'],
    senha: 'sage',
  },
  {
    id: 'p_111',
    nome: 'ITAERCIO PEREIRA DE LIMA',
    email: 'itaercio@sage.com',
    cpf: '111.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_41', 'd_42', 'd_7', 'd_38', 'd_39', 'd_2', 'd_43'],
    senha: 'sage',
  },
  {
    id: 'p_112',
    nome: 'IVANEIDE ALVES DE ARAUJO',
    email: 'ivaneide@sage.com',
    cpf: '112.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_44', 'd_45', 'd_46', 'd_47', 'd_9'],
    senha: 'sage',
  },
  {
    id: 'p_113',
    nome: 'JO├âO IGOR GOMES DE SOUZA',
    email: 'jo├úo@sage.com',
    cpf: '113.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_48', 'd_49', 'd_50', 'd_23'],
    senha: 'sage',
  },
  {
    id: 'p_114',
    nome: 'TAMIRES SANTIAGO DOS SANTOS FERNANDES',
    email: 'tamires@sage.com',
    cpf: '114.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_14', 'd_15', 'd_66', 'd_13'],
    senha: 'sage',
  },
  {
    id: 'p_115',
    nome: 'LUCICLEIDE CARLOS TEIXEIRA',
    email: 'lucicleide@sage.com',
    cpf: '115.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_51', 'd_52', 'd_53'],
    senha: 'sage',
  },
  {
    id: 'p_116',
    nome: 'LUIZ GOMES DE OLIVEIRA NETO',
    email: 'luiz@sage.com',
    cpf: '116.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_7', 'd_29', 'd_25', 'd_54', 'd_55', 'd_42'],
    senha: 'sage',
  },
  {
    id: 'p_117',
    nome: 'MARCOS ANDR├ë QUEIROZ MACHADO',
    email: 'marcos@sage.com',
    cpf: '117.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_42', 'd_38', 'd_56', 'd_39'],
    senha: 'sage',
  },
  {
    id: 'p_118',
    nome: 'MARCOS JOSE BENTO',
    email: 'marcos@sage.com',
    cpf: '118.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_26', 'd_57', 'd_58', 'd_27', 'd_59', 'd_60', 'd_61', 'd_62'],
    senha: 'sage',
  },
  {
    id: 'p_119',
    nome: 'MARIA JACKELINE PEREIRA DE LIMA',
    email: 'maria@sage.com',
    cpf: '119.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_63', 'd_64', 'd_23', 'd_65'],
    senha: 'sage',
  },
  {
    id: 'p_120',
    nome: 'MIKAEL FERREIRA DE LIMA',
    email: 'mikael@sage.com',
    cpf: '120.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_67', 'd_68', 'd_69'],
    senha: 'sage',
  },
  {
    id: 'p_121',
    nome: 'MORGANIA ALVES DE AMORIM',
    email: 'morgania@sage.com',
    cpf: '121.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_70', 'd_71'],
    senha: 'sage',
  },
  {
    id: 'p_122',
    nome: 'NACIZO CANDIDO NETO',
    email: 'nacizo@sage.com',
    cpf: '122.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_72', 'd_45', 'd_73', 'd_47'],
    senha: 'sage',
  },
  {
    id: 'p_123',
    nome: 'N├üJILA RAQUEL MOREIRA DA SILVA',
    email: 'n├íjila@sage.com',
    cpf: '123.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_74', 'd_46'],
    senha: 'sage',
  },
  {
    id: 'p_124',
    nome: 'PAULO VICTOR ARAUJO RICARTE',
    email: 'paulo@sage.com',
    cpf: '124.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_34', 'd_25', 'd_75', 'd_76', 'd_77'],
    senha: 'sage',
  },
  {
    id: 'p_125',
    nome: 'REGILANIA OLIVEIRA DO NASCIMENTO',
    email: 'regilania@sage.com',
    cpf: '125.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_25', 'd_44', 'd_45', 'd_47', 'd_78'],
    senha: 'sage',
  },
  {
    id: 'p_126',
    nome: 'RENATO SIQUEIRA',
    email: 'renato@sage.com',
    cpf: '126.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_79', 'd_80'],
    senha: 'sage',
  },
  {
    id: 'p_127',
    nome: 'SILAS MICAEL DO NASCIMENTO GOMES',
    email: 'silas@sage.com',
    cpf: '127.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_25', 'd_51', 'd_81', 'd_82', 'd_80', 'd_83'],
    senha: 'sage',
  },
  {
    id: 'p_128',
    nome: 'THAIANA MAGNA MOURA SALDANHA',
    email: 'thaiana@sage.com',
    cpf: '128.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_51', 'd_83'],
    senha: 'sage',
  },
  {
    id: 'p_129',
    nome: 'TAIS NUNES LEMOS',
    email: 'tais@sage.com',
    cpf: '129.111.111-11',
    perfil: 'professor',
    status: 'ativo',
    dataCadastro: '2026-01-01T08:00:00Z',
    disciplinasLecionadas: ['d_84', 'd_85', 'd_86', 'd_87', 'd_13', 'd_14', 'd_15', 'd_9', 'd_27'],
    senha: 'sage',
  }

export const MOCK_DISCIPLINAS: Disciplina[] = [
  { id: 'd_1', nome: 'AEE MANH├â', serie: 'Todas', cargaHoraria: 14, status: 'ativa' },
  { id: 'd_2', nome: 'QU├ìMICA', serie: '1┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_3', nome: 'CNT ENEM', serie: '3┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_4', nome: 'QU├ìMICA', serie: '3┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_5', nome: 'AP. MAT', serie: '2┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_6', nome: 'MAT ENEM', serie: '3┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_7', nome: 'PCA', serie: 'Todas', cargaHoraria: 9, status: 'ativa' },
  { id: 'd_8', nome: 'MATEM├üTICA', serie: '3┬¬ S├®rie', cargaHoraria: 3, status: 'ativa' },
  { id: 'd_9', nome: 'UCE CNT', serie: 'Todas', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_10', nome: 'ED. F├ìSICA', serie: '3┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_11', nome: 'ED.FIS. INT', serie: '3┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_12', nome: 'BIOLOGIA', serie: '3┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_13', nome: 'ESTUDO ORIENTADO', serie: '2┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_14', nome: 'F. CID', serie: '2┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_15', nome: 'PPDT', serie: '2┬¬ S├®rie', cargaHoraria: 3, status: 'ativa' },
  { id: 'd_16', nome: 'CULTURA DIGITAL', serie: '3┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_17', nome: 'GEOGRAFIA', serie: '3┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_18', nome: 'Coord. Multimeios / Manh├ú', serie: 'Todas', cargaHoraria: 14, status: 'ativa' },
  { id: 'd_19', nome: 'Coord. Multimeios / Tarde', serie: 'Todas', cargaHoraria: 13, status: 'ativa' },
  { id: 'd_20', nome: 'HIST├ôRIA', serie: '1┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_21', nome: 'CHS ENEM', serie: '3┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_22', nome: 'HIST├ôRIA', serie: '2┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_23', nome: 'UCE CHS', serie: 'Todas', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_24', nome: 'AEE TARDE', serie: 'Todas', cargaHoraria: 13, status: 'ativa' },
  { id: 'd_25', nome: 'OPTATIVA', serie: 'Todas', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_26', nome: 'UCE  EPT', serie: 'Todas', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_27', nome: 'UCE  CLUBE', serie: '1┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_28', nome: 'L├ìNGUA PORTUGUESA', serie: '3┬¬ S├®rie', cargaHoraria: 3, status: 'ativa' },
  { id: 'd_29', nome: 'UCE  LGG', serie: 'Todas', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_30', nome: 'L├ìNGUA PORTUGUESA', serie: '1┬¬ S├®rie', cargaHoraria: 3, status: 'ativa' },
  { id: 'd_31', nome: 'UCE  LGG', serie: '1┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_32', nome: 'IFA LGG', serie: '2┬¬ S├®rie', cargaHoraria: 4, status: 'ativa' },
  { id: 'd_33', nome: 'LGG ENEM', serie: '3┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_34', nome: 'LEI', serie: 'Todas', cargaHoraria: 13, status: 'ativa' },
  { id: 'd_35', nome: 'ARTES', serie: '1┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_36', nome: 'ARTES', serie: '2┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_37', nome: 'ARTES', serie: '3┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_38', nome: 'F. CID', serie: '3┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_39', nome: 'PPDT', serie: '3┬¬ S├®rie', cargaHoraria: 3, status: 'ativa' },
  { id: 'd_40', nome: 'HIST├ôRIA', serie: '3┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_41', nome: 'CULTURA DIGITAL', serie: '2┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_42', nome: 'EST. ORIENTADO', serie: '3┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_43', nome: 'QU├ìMICA', serie: '2┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_44', nome: 'ESTUDO ORIENTADO', serie: '1┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_45', nome: 'F. CID', serie: '1┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_46', nome: 'NTPPS', serie: '2┬¬ S├®rie', cargaHoraria: 4, status: 'ativa' },
  { id: 'd_47', nome: 'PPDT', serie: '1┬¬ S├®rie', cargaHoraria: 3, status: 'ativa' },
  { id: 'd_48', nome: 'FILOSOFIA', serie: '1┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_49', nome: 'FILOSOFIA', serie: '2┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_50', nome: 'FILOSOFIA', serie: '3┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_51', nome: 'LEC', serie: 'Todas', cargaHoraria: 15, status: 'ativa' },
  { id: 'd_52', nome: 'BIOLOGIA', serie: '1┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_53', nome: 'BIOLOGIA', serie: '2┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_54', nome: 'AP. LP', serie: '2┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_55', nome: 'L├ìNGUA PORTUGUESA', serie: '2┬¬ S├®rie', cargaHoraria: 3, status: 'ativa' },
  { id: 'd_56', nome: 'MATEM├üTICA', serie: '2┬¬ S├®rie', cargaHoraria: 4, status: 'ativa' },
  { id: 'd_57', nome: 'L├ìNGUA ESPANHOLA', serie: '1┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_58', nome: 'L├ìNGUA INGLESA', serie: '1┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_59', nome: 'L├ìNGUA ESPANHOLA', serie: '2┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_60', nome: 'L├ìNGUA INGLESA', serie: '2┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_61', nome: 'L├ìNGUA ESPANHOLA', serie: '3┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_62', nome: 'L├ìNGUA INGLESA', serie: '3┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_63', nome: 'CULTURA DIGITAL', serie: '1┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_64', nome: 'GEOGRAFIA', serie: '2┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_65', nome: 'IFA CHS', serie: '2┬¬ S├®rie', cargaHoraria: 4, status: 'ativa' },
  { id: 'd_66', nome: 'IFA CNT', serie: '2┬¬ S├®rie', cargaHoraria: 4, status: 'ativa' },
  { id: 'd_67', nome: 'SOCIOLOGIA', serie: '1┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_68', nome: 'SOCIOLOGIA', serie: '2┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_69', nome: 'SOCIOLOGIA', serie: '3┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_70', nome: 'Pedagogo Multimeios / Manh├ú', serie: 'Todas', cargaHoraria: 20, status: 'ativa' },
  { id: 'd_71', nome: 'Pedagogo Multimeios / Tarde', serie: 'Todas', cargaHoraria: 20, status: 'ativa' },
  { id: 'd_72', nome: 'EST. ORIENTADO', serie: '1┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_73', nome: 'GEOGRAFIA', serie: '1┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_74', nome: 'NTPPS', serie: '1┬¬ S├®rie', cargaHoraria: 4, status: 'ativa' },
  { id: 'd_75', nome: 'REDA├ç├âO', serie: '1┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_76', nome: 'REDA├ç├âO', serie: '2┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_77', nome: 'REDA├ç├âO', serie: '3┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_78', nome: 'F├ìSICA', serie: '3┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_79', nome: 'NTPPS', serie: '3┬¬ S├®rie', cargaHoraria: 4, status: 'ativa' },
  { id: 'd_80', nome: 'UCE MAT', serie: 'Todas', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_81', nome: 'F├ìSICA', serie: '1┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_82', nome: 'MATEM├üTICA', serie: '1┬¬ S├®rie', cargaHoraria: 4, status: 'ativa' },
  { id: 'd_83', nome: 'F├ìSICA', serie: '2┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_84', nome: 'ED. F├ìSICA', serie: '1┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_85', nome: 'ED. F├ìSICA', serie: '2┬¬ S├®rie', cargaHoraria: 1, status: 'ativa' },
  { id: 'd_86', nome: 'ED.FIS. INT', serie: '1┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' },
  { id: 'd_87', nome: 'ED.FIS. INT', serie: '2┬¬ S├®rie', cargaHoraria: 2, status: 'ativa' }

;

export const MOCK_PLANOS: PlanoAula[] = [
  {
    _id: 'p1',
    professorId: '1',
    professorNome: 'Maria Silva',
    disciplina: 'Matemática',
    turma: '1ª Série',
    mesAno: '2026-03',
    objetivos: 'Desenvolver o raciocínio lógico-matemático através de operações básicas e resolução de problemas contextualizados.',
    conteudo: 'Números naturais, adição e subtração, problemas do cotidiano.',
    avaliacao: 'Avaliação contínua através de exercícios em sala e participação.',
    semanas: [
      { numero: 1, metodologia: 'Aula expositiva com material concreto (blocos lógicos). Atividade em duplas para contagem.', recursos: 'Blocos lógicos, quadro branco, fichas numeradas.' },
      { numero: 2, metodologia: 'Jogos matemáticos em grupo. Resolução de problemas no caderno.', recursos: 'Jogos de tabuleiro, caderno, lápis coloridos.' },
      { numero: 3, metodologia: 'Atividade prática: mercadinho simulado para trabalhar adição e subtração.', recursos: 'Cédulas e moedas de brinquedo, etiquetas de preço.' },
      { numero: 4, metodologia: 'Revisão com quiz interativo e avaliação individual escrita.', recursos: 'Projetor, folhas de avaliação impressas.' },
    ],
    status: 'finalizado',
    criadoEm: '2026-02-28T10:00:00Z',
    atualizadoEm: '2026-03-05T14:30:00Z',
  },
  {
    _id: 'p2',
    professorId: '1',
    professorNome: 'Maria Silva',
    disciplina: 'Português',
    turma: '2ª Série',
    mesAno: '2026-03',
    objetivos: 'Aprimorar a leitura e interpretação de textos curtos, ampliando o vocabulário.',
    conteudo: 'Leitura de contos e fábulas, interpretação textual, ortografia.',
    avaliacao: 'Produção textual e leitura em voz alta.',
    semanas: [
      { numero: 1, metodologia: 'Roda de leitura com conto "A Cigarra e a Formiga". Discussão oral.', recursos: 'Livro de fábulas, almofadas para roda de leitura.' },
      { numero: 2, metodologia: 'Atividade de reescrita do conto com desenho. Trabalho individual.', recursos: 'Folhas pautadas, lápis de cor, borracha.' },
      { numero: 3, metodologia: 'Ditado de palavras do conto. Atividade em duplas de ortografia.', recursos: 'Caderno, dicionário ilustrado.' },
    ],
    status: 'rascunho',
    criadoEm: '2026-03-01T08:00:00Z',
    atualizadoEm: '2026-03-01T08:00:00Z',
  },
  {
    _id: 'p3',
    professorId: '2',
    professorNome: 'Carlos Oliveira',
    disciplina: 'Ciências',
    turma: '3ª Série',
    mesAno: '2026-03',
    objetivos: 'Compreender o ciclo da água e sua importância para o meio ambiente.',
    conteudo: 'Ciclo da água, estados físicos, preservação ambiental.',
    avaliacao: 'Maquete do ciclo da água e apresentação oral.',
    semanas: [
      { numero: 1, metodologia: 'Vídeo sobre ciclo da água seguido de debate em sala.', recursos: 'Projetor, vídeo educativo, caderno.' },
      { numero: 2, metodologia: 'Experimento: evaporação e condensação com materiais simples.', recursos: 'Copos, água, plástico filme, gelo.' },
      { numero: 3, metodologia: 'Construção de maquete do ciclo da água em grupos.', recursos: 'Isopor, tinta guache, algodão, cola.' },
      { numero: 4, metodologia: 'Apresentação das maquetes e avaliação oral.', recursos: 'Maquetes prontas, rubrica de avaliação.' },
    ],
    status: 'finalizado',
    criadoEm: '2026-02-25T09:00:00Z',
    atualizadoEm: '2026-03-04T11:00:00Z',
  },
  {
    _id: 'p4',
    professorId: '1',
    professorNome: 'Maria Silva',
    disciplina: 'História',
    turma: '1ª Série',
    mesAno: '2026-02',
    objetivos: 'Reconhecer a importância da família e da comunidade na formação da identidade.',
    conteudo: 'Família, comunidade, identidade cultural.',
    avaliacao: 'Desenho da árvore genealógica e relato oral.',
    semanas: [
      { numero: 1, metodologia: 'Conversa sobre família. Cada aluno apresenta foto da família.', recursos: 'Fotos trazidas de casa, mural da sala.' },
      { numero: 2, metodologia: 'Construção da árvore genealógica com recortes e colagem.', recursos: 'Cartolina, cola, tesoura, revistas.' },
    ],
    status: 'finalizado',
    criadoEm: '2026-01-28T10:00:00Z',
    atualizadoEm: '2026-02-10T16:00:00Z',
  },
];
